version: '3'
services:
  app:
    image: node:14
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/videotranscoder
      - JWT_SECRET=your_jwt_secret
      - PORT=3000
    depends_on:
      - mongo
    command: npm start

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data:
